id: I3DFC71D8
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 15:12:17.890744
last_modified: 2023-02-09 15:12:17.890839
source_metadata:
  title: 'MSV 1,17: Saṃghabhedavastu'
  language: bo
bases:
  '2818':
    base_file: 2818.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
